python task_1_test_1.py
python task_2_test_1.py
python task_2_test_2.py
python task_3_test_1.py
python task_3_test_2.py
python task_4_test_1.py
python task_4_test_2.py
python task_5_test_1.py
python task_5_test_2.py
python task_5_test_3.py